<a href="https://colab.research.google.com/github/ftmshifa777/Pandas-Test-Code/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Test Code

In [ ]:
import pandas as pd

A series is one dimentional labelled data structure.

* Contains values and  an index

In [ ]:
marks=pd.Series([80,75,90,85])

In [ ]:
print(marks)

0    80
1    75
2    90
3    85
dtype: int64

80,75, 85,90 -> values

0,1,2,3 -> index/labels

 It is one dimensional  -> like a single column of data




 We can also create our own custom labels Custom Index

# Data frame

A Dataframe is a two dimensional table containing rows and columns.

In [ ]:
data={"Name":["John", "Arun","Arjun"],
      "Age":[23,24,25],
      "Marks":[89,90,87]}

In [ ]:
df

    Name  Age  Marks
0   John   23     89
1   Arun   24     90
2  Arjun   25     87

# Inspecting Data

In [ ]:
df.head()

    Name  Age  Marks
0   John   23     89
1   Arun   24     90
2  Arjun   25     87

In [ ]:
df.tail()

    Name  Age  Marks
0   John   23     89
1   Arun   24     90
2  Arjun   25     87

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [ ]:
df.describe()

        Age      Marks
count   3.0   3.000000
mean   24.0  88.666667
std     1.0   1.527525
min    23.0  87.000000
25%    23.5  88.000000
50%    24.0  89.000000
75%    24.5  89.500000
max    25.0  90.000000

In [ ]:
df.shape

(3, 3)

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
df.dtypes

Name     object
Age       int64
Marks     int64
dtype: object

In [ ]:
# Selecting Data

In [ ]:
df["Name"]

0     John
1     Arun
2    Arjun
Name: Name, dtype: object

In [ ]:
df[["Name", "Marks"]]

    Name  Marks
0   John     89
1   Arun     90
2  Arjun     87

loc and iloc are used to select data from a series or dataframe.

loc -> selects using labels

iloc -> selects using integer positions

In [ ]:
df.loc[0]

Name     John
Age        23
Marks      89
Name: 0, dtype: object

In [ ]:
df.loc[0,"Name"]

'John'

In [ ]:
df.iloc[0]

Name     John
Age        23
Marks      89
Name: 0, dtype: object

In [ ]:
df.iloc[0,1]

np.int64(23)

# Data Manipulation

Add a column

In [ ]:
df["Passed"]=df["Marks"]>=90

In [ ]:
df

    Name  Age  Marks  Passed
0   John   23     89   False
1   Arun   24     90    True
2  Arjun   25     87   False

# Calculated Column

In [ ]:
df["Bonus"]=df["Marks"]+5
df

    Name  Age  Marks  Passed  Bonus
0   John   23     89   False     94
1   Arun   24     90    True     95
2  Arjun   25     87   False     92

# Modify Column

In [ ]:
df["Marks"]=df["Marks"]+2

In [ ]:
df

    Name  Age  Marks  Passed  Bonus
0   John   23     96   False     94
1   Arun   24     97    True     95
2  Arjun   25     94   False     92

# Drop Column

In [ ]:
df=df.drop(columns=["Bonus"])

In [ ]:
df

    Name  Age  Marks  Passed
0   John   23     96   False
1   Arun   24     97    True
2  Arjun   25     94   False

# Rename Columns

In [ ]:
df=df.rename(columns={"Marks":"Score"})

In [ ]:
df

    Name  Age  Score  Passed
0   John   23     96   False
1   Arun   24     97    True
2  Arjun   25     94   False