<a href="https://colab.research.google.com/github/ftmshifa777/Pandas-Test-Code/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Test Code

In [3]:
import pandas as pd

A series is one dimentional labelled data structure.

* Contains values and  an index

In [4]:
marks=pd.Series([80,75,90,85])

In [5]:
print(marks)

0    80
1    75
2    90
3    85
dtype: int64

80,75, 85,90 -> values

0,1,2,3 -> index/labels

 It is one dimensional  -> like a single column of data




 We can also create our own custom labels Custom Index

# Data frame

A Dataframe is a two dimensional table containing rows and columns.

In [6]:
data={"Name":["John", "Arun","Arjun"],
      "Age":[23,24,25],
      "Marks":[89,90,87]}

In [7]:
df=pd.DataFrame(data)

# Inspecting Data

In [8]:
df.head()

    Name  Age  Marks
0   John   23     89
1   Arun   24     90
2  Arjun   25     87

In [9]:
df.tail()

    Name  Age  Marks
0   John   23     89
1   Arun   24     90
2  Arjun   25     87

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [11]:
df.describe()

        Age      Marks
count   3.0   3.000000
mean   24.0  88.666667
std     1.0   1.527525
min    23.0  87.000000
25%    23.5  88.000000
50%    24.0  89.000000
75%    24.5  89.500000
max    25.0  90.000000

In [12]:
df.shape

(3, 3)

In [13]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [14]:
df.dtypes

Name     object
Age       int64
Marks     int64
dtype: object

In [15]:
# Selecting Data

In [16]:
df["Name"]

0     John
1     Arun
2    Arjun
Name: Name, dtype: object

In [17]:
df[["Name", "Marks"]]

    Name  Marks
0   John     89
1   Arun     90
2  Arjun     87

loc and iloc are used to select data from a series or dataframe.

loc -> selects using labels

iloc -> selects using integer positions

In [18]:
df.loc[0]

Name     John
Age        23
Marks      89
Name: 0, dtype: object

In [19]:
df.loc[0,"Name"]

'John'

In [20]:
df.iloc[0]

Name     John
Age        23
Marks      89
Name: 0, dtype: object

In [21]:
df.iloc[0,1]

np.int64(23)

# Data Manipulation

Add a column

In [22]:
df["Passed"]=df["Marks"]>=90

In [23]:
df

    Name  Age  Marks  Passed
0   John   23     89   False
1   Arun   24     90    True
2  Arjun   25     87   False

# Calculated Column

In [24]:
df["Bonus"]=df["Marks"]+5
df

    Name  Age  Marks  Passed  Bonus
0   John   23     89   False     94
1   Arun   24     90    True     95
2  Arjun   25     87   False     92

# Modify Column

In [25]:
df["Marks"]=df["Marks"]+2

In [26]:
df

    Name  Age  Marks  Passed  Bonus
0   John   23     91   False     94
1   Arun   24     92    True     95
2  Arjun   25     89   False     92

# Drop Column

In [27]:
df=df.drop(columns=["Bonus"])

In [28]:
df

    Name  Age  Marks  Passed
0   John   23     91   False
1   Arun   24     92    True
2  Arjun   25     89   False

# Rename Columns

In [29]:
df=df.rename(columns={"Marks":"Score"})

In [30]:
df

    Name  Age  Score  Passed
0   John   23     91   False
1   Arun   24     92    True
2  Arjun   25     89   False

# Filter rows

df["Marks"] >80 checks each value in the marks column and produces true or flse. d[..] then keeping only the true one.

In [31]:
df[ df["Score"]>90]

   Name  Age  Score  Passed
0  John   23     91   False
1  Arun   24     92    True

#Multiple Conditions

In [34]:
df[(df['Score']> 80)
&(df['Age']<24)]

   Name  Age  Score  Passed
0  John   23     91   False

#OR Condition

In [35]:
df[ (df['Score']>80)
|
    (df['Age']>24)]

    Name  Age  Score  Passed
0   John   23     91   False
1   Arun   24     92    True
2  Arjun   25     89   False

#isin()

isin() is used to filter rows where a column value matches any values from the given list

In [38]:
df[df['Name'].isin(['John','Arun'])]

   Name  Age  Score  Passed
0  John   23     91   False
1  Arun   24     92    True

# sort_values()

sort_values() is used to sort the rows of a dataframe based on the vlaues in one or more columns

In [39]:
df.sort_values('Score',ascending=True)

    Name  Age  Score  Passed
2  Arjun   25     89   False
0   John   23     91   False
1   Arun   24     92    True

In [40]:
df.sort_values("Score", ascending=False)

    Name  Age  Score  Passed
1   Arun   24     92    True
0   John   23     91   False
2  Arjun   25     89   False

# Missing Values

In [41]:
import pandas as pd

df = pd.DataFrame({
    "Name": [
        "John",
        "Anu",
        "Rahul",
        "Meera",
        "Arjun",
        "Diya",
        "Vishnu",
        "Neha"
    ],
    "Age": [
        21,
        22,
        None,
        20,
        23,
        None,
        21,
        22
    ],
    "Course": [
        "Python",
        "SQL",
        "Python",
        None,
        "ML",
        "SQL",
        None,
        "Python"
    ],
    "Marks": [
        85,
        None,
        72,
        90,
        None,
        68,
        95,
        None
    ]
})

In [42]:
df

     Name   Age  Course  Marks
0    John  21.0  Python   85.0
1     Anu  22.0     SQL    NaN
2   Rahul   NaN  Python   72.0
3   Meera  20.0    None   90.0
4   Arjun  23.0      ML    NaN
5    Diya   NaN     SQL   68.0
6  Vishnu  21.0    None   95.0
7    Neha  22.0  Python    NaN

#isnull()

isnull() is used to find missing/null values in a dataframe

In [43]:
df.isnull()

    Name    Age  Course  Marks
0  False  False   False  False
1  False  False   False   True
2  False   True   False  False
3  False  False    True  False
4  False  False   False   True
5  False   True   False  False
6  False  False    True  False
7  False  False   False   True

it checks every cell and returns:

True -> value is missing

False -> value is present

#df.isnull().sum()

This tells us how many missing values each cloumn contains

In [44]:
df.isnull().sum()

Name      0
Age       2
Course    2
Marks     3
dtype: int64

#dropna()

dropna() is used to remove rows that cotains missing values(NaN/None).

In [45]:
df=df.dropna()

now Pandas removes every containing atleast one missing value.

dropna() can remove a lot of data even if one column is missing.

In [46]:
df

   Name   Age  Course  Marks
0  John  21.0  Python   85.0

# Fill missing marks with 0

In [47]:
import pandas as pd

df = pd.DataFrame({
    "Name": [
        "John",
        "Anu",
        "Rahul",
        "Meera",
        "Arjun",
        "Diya",
        "Vishnu",
        "Neha"
    ],
    "Age": [
        21,
        22,
        None,
        20,
        23,
        None,
        21,
        22
    ],
    "Course": [
        "Python",
        "SQL",
        "Python",
        None,
        "ML",
        "SQL",
        None,
        "Python"
    ],
    "Marks": [
        85,
        None,
        72,
        90,
        None,
        68,
        95,
        None
    ]
})

In [48]:
df

     Name   Age  Course  Marks
0    John  21.0  Python   85.0
1     Anu  22.0     SQL    NaN
2   Rahul   NaN  Python   72.0
3   Meera  20.0    None   90.0
4   Arjun  23.0      ML    NaN
5    Diya   NaN     SQL   68.0
6  Vishnu  21.0    None   95.0
7    Neha  22.0  Python    NaN

fillna(0) is used to replace missing values (NaN) with 0 in a Pandas DataFrame or Series.

In [49]:
df['Marks'] =df['Marks'].fillna(0)

In [50]:
df['Marks']

0    85.0
1     0.0
2    72.0
3    90.0
4     0.0
5    68.0
6    95.0
7     0.0
Name: Marks, dtype: float64

# Filling Missing marks with Mean

In [56]:
import pandas as pd

df = pd.DataFrame({
    "Name": [
        "John",
        "Anu",
        "Rahul",
        "Meera",
        "Arjun",
        "Diya",
        "Vishnu",
        "Neha"
    ],
    "Age": [
        21,
        22,
        None,
        20,
        23,
        None,
        21,
        22
    ],
    "Course": [
        "Python",
        "SQL",
        "Python",
        None,
        "ML",
        "SQL",
        None,
        "Python"
    ],
    "Marks": [
        85,
        None,
        72,
        90,
        None,
        68,
        95,
        None
    ]
})

In [52]:
df

     Name   Age  Course  Marks
0    John  21.0  Python   85.0
1     Anu  22.0     SQL    NaN
2   Rahul   NaN  Python   72.0
3   Meera  20.0    None   90.0
4   Arjun  23.0      ML    NaN
5    Diya   NaN     SQL   68.0
6  Vishnu  21.0    None   95.0
7    Neha  22.0  Python    NaN

In [57]:
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
df['Marks']

0    85.0
1    82.0
2    72.0
3    90.0
4    82.0
5    68.0
6    95.0
7    82.0
Name: Marks, dtype: float64