<a href="https://colab.research.google.com/github/ftmshifa777/Pandas-Test-Code/blob/main/Pandas_Data_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [3]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [4]:
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [5]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [6]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [8]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [9]:
df.shape

(17000, 9)

In [10]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [11]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [14]:
df[["population","households"]]

       population  households
0          1015.0       472.0
1          1129.0       463.0
2           333.0       117.0
3           515.0       226.0
4           624.0       262.0
...           ...         ...
16995       907.0       369.0
16996      1194.0       465.0
16997      1244.0       456.0
16998      1298.0       478.0
16999       806.0       270.0

[17000 rows x 2 columns]

In [15]:
df.loc[0,"population"]

np.float64(1015.0)

In [16]:
df.iloc[0,0]

np.float64(-114.31)

In [17]:
df["Highly popular"]=df["population"]>2000
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Highly popular
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,False
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,False
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,False
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,False
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,False
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,False
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,False
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,False
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,False
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,False

In [18]:
df['extra_rooms']=df['total_rooms']+5

In [19]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Highly popular,extra_rooms
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,False,5617.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,False,7655.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,False,725.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,False,1506.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,False,1459.0
...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,False,2222.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,False,2354.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,False,2682.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,False,2677.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,False,1825.0

In [20]:
df['median_income']=df['median_income']+2
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Highly popular,extra_rooms
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,3.4936,66900.0,False,5617.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,3.8200,80100.0,False,7655.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,3.6509,85700.0,False,725.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,5.1917,73400.0,False,1506.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,3.9250,65500.0,False,1459.0
...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,4.3571,111400.0,False,2222.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,4.5179,79000.0,False,2354.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,5.0313,103600.0,False,2682.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,3.9797,85800.0,False,2677.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,5.0147,94600.0,False,1825.0

In [21]:
df.drop(columns="extra_rooms")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Highly popular
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,3.4936,66900.0,False
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,3.8200,80100.0,False
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,3.6509,85700.0,False
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,5.1917,73400.0,False
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,3.9250,65500.0,False
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,4.3571,111400.0,False
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,4.5179,79000.0,False
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,5.0313,103600.0,False
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,3.9797,85800.0,False
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,5.0147,94600.0,False

In [22]:
df=df.rename(columns={"median_income":"new_med_income"})

In [23]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,new_med_income,median_house_value,Highly popular,extra_rooms
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,3.4936,66900.0,False,5617.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,3.8200,80100.0,False,7655.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,3.6509,85700.0,False,725.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,5.1917,73400.0,False,1506.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,3.9250,65500.0,False,1459.0
...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,4.3571,111400.0,False,2222.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,4.5179,79000.0,False,2354.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,5.0313,103600.0,False,2682.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,3.9797,85800.0,False,2677.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,5.0147,94600.0,False,1825.0

In [24]:
df[df["households"]>400]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,new_med_income,median_house_value,Highly popular,extra_rooms
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,3.4936,66900.0,False,5617.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,3.8200,80100.0,False,7655.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,4.6768,82400.0,False,2912.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,4.1782,58400.0,True,4794.0
10,-114.60,33.62,16.0,3741.0,801.0,2434.0,824.0,4.6797,86500.0,True,3746.0
...,...,...,...,...,...,...,...,...,...,...,...
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,4.4805,73200.0,False,3164.0
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,5.0806,106700.0,False,2699.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,4.5179,79000.0,False,2354.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,5.0313,103600.0,False,2682.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,3.9797,85800.0,False,2677.0